# Generated by Django 5.1rc1 on 2025-01-06 16:07

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receiptreader', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_spent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('category_avg', models.JSONField(default=dict)),
                ('category_summary', models.JSONField(default=dict)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='summary', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
