# Generated by Django 5.1rc1 on 2025-01-15 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receiptreader', '0003_alter_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='text',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
